config/routes.rb
Rails.application.routes.draw do
 # root "HomePage"
  get "/cars", to: "car#all_cars"

  get "/cars/:id", to: "car#view_car"
  get "/car/new", to: "car#new"
  post '/cars', to: 'car#create'

 resources :cars
  get "/ViewCar", to: "car#view_car"

end



Rails.application.routes.draw do
  root "driversandcars#HomePage"
  get "/", to: "driversandcars#HomePage"

  get "/drivers", to: "driver#index"
  get "/drivers/:id", to: "driver#show"
  get "/driver/new", to: "driver#new"
  post '/drivers', to: 'driver#create'
post "/driversandcars/select_car",to:"driversandcars#select_car"
post "/driversandcars/select_driver",to:"driversandcars#select_driver"

post "/driversandcars/submit",to:"driversandcars#submit"
  get "driversandcars", to: "driversandcars#index"
  resources :drivers
  # resources :articles do
  #   resources :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    validates :title, presence: true
    has_many :links
    has_many :drivers, through: :links
end

app/models/driver.rb
class Driver < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    has_many :links
    has_many :cars, through: :links
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :driver
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/car_controller.rb
class CarController < ApplicationController
  def new
    @car = Car.new
  end

  def all_cars
    @cars=Car.all
  end
  
  def view_car
@car=Car.find(params[:id])
  end
  

  def create
    @car = Car.new(car_params)
    @car.save
    if @car.save
      redirect_to @car
    else
      render :new
    end
  end

  private
    def car_params
      params.require(:car).permit(:title, :type_car,:color)
    end
end

app/controllers/driver_controller.rb
class DriverController < ApplicationController
  def index
    @drivers=Driver.all
  end
  def show
    @driver = Driver.find(params[:id])
  end

  def new
    @driver = Driver.new
  end

  def create
    @driver = Driver.new(drivers_params)
    @driver.save

    if @driver.save
      redirect_to @driver
    else
      render :action => :index
    end
  end

  private
    def drivers_params
      params.require(:driver).permit(:name, :email,:birth)
    end
end

app/controllers/driversandcars_controller.rb
class DriversandcarsController < ApplicationController
  def index
    @drivers=Driver.all
    @cars=Car.all
  end

  def select_car 
    @carSelectedID = params[:optionValue]
    @carSelected=Car.find(@carSelectedID)
    @links=Link.where(car:@carSelected)
    @drivers=[]
    @links.each do |link|
      @drivers.append(Driver.find(link.driver_id).name)
    end
    render json: {links: @links,drivers:@drivers}
  end 
  
  def select_driver 
    @driverSelectedID = params[:optionValue]
    @driverSelected=Driver.find(@driverSelectedID)
    @links=Link.where(driver:@driverSelected)
    @cars=[]
    @links.each do |link|
      @cars.append(Car.find(link.car_id).title)
    end
    render json: {links: @links,cars:@cars}

  end 
  def submit

    @carSelectedID = params[:car]
    @carSelected=Car.find(@carSelectedID)
    @driverSelectedID = params[:driver]
    @driverSelected=Driver.find(@driverSelectedID)
    @links=Link.find_by(car:@carSelected,driver:@driverSelected)
    if @links ==nil
      @newLink=Link.new(car:@carSelected,driver:@driverSelected)
      @newLink.save
      if @newLink.save
        render json: {text:"Connect car to driver - sucsses"}
      else
         render json: {text:"Connect car to driver - faild"}
      end
    else
      render json: {text:"This car and driver has connected"}
    end


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/helpers/driversandcars_helper.rb
module DriversandcarsHelper
end

app/helpers/my_cars_helper.rb
module MyCarsHelper
end

app/helpers/nisui_helper.rb
module NisuiHelper
end

app/views/car/all_cars.html.erb
<h1>Cars</h1>

<div id=container>
<table class="table table-striped table-hover">


<thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">title</th>
      <th scope="col">type</th>
      <th scope="col">color</th>
    </tr>
  </thead>
  <tbody>
<% @cars.each do |car| %>
    <tr class='clickable-row' data-href="<%= car_path(car) %>">
      <th scope="row"><%= car.id %></th>
      <td><%= car.title %></td>
      <td>
       <%= car.type_car %> 
      </td>
      <td><%= car.color %></td>
    </tr>
  

  <% end %>
</table>
</div>
 <a href="car/new">
       New Car
      </a>
<script>
// $("#container").on('click-row.bs.table', function (e, row, $element) {
//     window.location = $element.data('href');
// });

jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.location = $(this).data("href");
    });
});
</script>

app/views/car/index.html.erb
  <main class="px-3">
    <h1>Cover your page.</h1>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>
  </main>

app/views/car/new.html.erb
<h1>New Car</h1>
<div style="width: 70%;
    margin: auto;
    margin-top: inherit;
    padding-top: 30px;">
<%= form_with model: @car do |form| %>
  <div class="form-group">

    <%= form.label :title %><br>
    <%= form.text_field :title,class: 'form-control' %>
    <% @car.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :type%><br>
    <%= form.text_area :type_car,class: 'form-control' %>
  </div>

  <div class="form-group" style='padding-bottom:20px'>
    <%= form.label :color %><br>
<%= form.select(:color, ["choose color",  "blue","yellow","red"], { :class => 'form-control' }) %>

  </div>

  <div class="form-group">
    <%= form.submit 'Submit' , :class=>'btn btn-primary'%>

  </div>
<% end %>
</div>

app/views/car/view_car.html.erb
<div class="card" style="width: 18rem;">

<% if @car.color == 'red' %>
  <%=image_tag ("red.jpg")%> 
<% elsif @car.color == 'blue'%>
   <%=image_tag ("blue.jpg")%> 
<% else %>
   <%=image_tag ("yellow.jpg")%> 

<% end %>


  <div class="card-body">
    <h3 class="card-title"><%= @car.title %></h3>
    <p class="card-text">Type:<%= @car.type_car %> </p>
        <p class="card-text">Color:<%= @car.color %> </p>

  </div>
</div>
<%= link_to "Cars list", cars_path %>

app/views/driver/index.html.erb
<h1>Drivers</h1>



<div id=container>
<table class="table table-striped table-hover">

<thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Birth date</th>
    </tr>
  </thead>
  <tbody>
  <% if @drivers !=nil %>
  <%@drivers.each do |driver| %>
     <tr class='clickable-row' data-href="<%= driver_path(driver) %>">
      <th scope="row"><%= driver.id %></th>
      <td><%= driver.name %></td>
      <td>
       <%= driver.email %>
      </td>
      <td><%= driver.birth %></td>
    </tr>
    <% end %>

  <% end %>
</table>
</div>
 <a href="driver/new">
       New Driver
      </a>
<script>
// $("#container").on('click-row.bs.table', function (e, row, $element) {
//     window.location = $element.data('href');
// });

jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.location = $(this).data("href");
    });
});
</script>

app/views/driver/new.html.erb
<h1>New Driver</h1>
	<%= flash[:notice] %>
<div style="width: 70%;margin: auto; margin-top: inherit; padding-top: 30px;">
<%= form_with model: Driver.new do |form| %>

 <div class="form-group">
    <%= form.label :name  %><br>
    <%= form.text_field :name,class: 'form-control' %>
    <% @driver.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :email %><br>
    <%= form.email_field :email,class: 'form-control' %>
        <% @driver.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

 <div class="form-group" style='padding-bottom:20px'>
    <%= form.label :birth_date %><br>
<%= form.date_field :birth,class: 'form-control datepicker' %>
  </div>

  <div class="form-group">
    <%= form.submit  'Submit' , :class=>'btn btn-primary'%>
  </div>
<% end %>

</div>

app/views/driver/show.html.erb
<div class="card" style="width: 18rem;">

  <%=image_tag ("driver.png")%> 
  <div class="card-body">
    <h3 class="card-title"><%= @driver.name %></h3>
    <p class="card-text">Email:<%=  @driver.email %> </p>
        <p class="card-text">Birth date:<%= @driver.birth %> </p>

  </div>
</div>
<%= link_to "Drivers list", drivers_path %>

app/views/driversandcars/HomePage.html.erb
  <main class="px-3">
  <div style="text-align:center">
    <p style="font-size: 5.5rem;">Welcome</p>
        <p style="font-size: 4.5rem;">My car application</p>
</div>
    <%=image_tag "car.png", style: 'height:auto;width:650px;'%> 

  </main>

app/views/driversandcars/index.html.erb
 <div class="row" style=    "padding-bottom: 20px;    padding-top: 50px;">
  <div class="col">
 <h3> choose car</h3>
 <select class="form-select cmbx_cars" aria-label="Default select example">
<option selected></option>

    <% @cars.each do |car| %>
  <option value="<%= car.id %>"><%= car.title %></option>
<% end %>
</select>
</div>
<div class="col text-center">
<button id="submitBtn" type="submit" class="btn btn-primary text-center" style="width:50%; margin-inline: auto;height:80px;">Connect</button>
</div>
  <div class="col">

<h3>choose driver</h3>
<select class="cmbx_drivers form-select" id="cmbx_drivers">
<option selected></option>
<% @drivers.each do |driver| %>
  <option value="<%= driver.id %>"><%= driver.name %></option>
<% end %>
</select>
</div>
</div>
<div class="row">
  <div class="col">

<table class="ResulsTableCar table table-striped" style="padding-top:20px;    min-height: 100px;">

</table>
</div>
  <div class="col">

<table class="ResulsTableDriver table table-striped" style="padding-top:20px;    min-height: 100px;">

</table>
</div>
</div>
<div class="submitResult">



</div>
<style>
.cover-container {
    max-width: 60em;
}
.inner{
  padding-left: 184px;

}
</style>
<script>
// $("#container").on('click-row.bs.table', function (e, row, $element) {
//     window.location = $element.data('href');
// });

jQuery(document).ready(function($) {
    $(".cmbx_cars").change(function() {
      $(".submitResult").html("")
  printTbleDriver();
    });

    $(".cmbx_drivers").change(function() {
      $(".submitResult").html("")
printTableCar();
    });
function printTbleDriver(){
      var optionValue =$(".cmbx_cars").val();
         if (optionValue) {
      $.ajax({
          type:    "POST",
          url:     "/driversandcars/select_car",
          data:    {optionValue: optionValue },
          success: function(data){
            var links=data.links 
            if(links.length!=0)
            {
                $(".ResulsTableCar").html("<tr><th>id</th><th>name</th><th>created_at</th></tr>")
                for (index = 0; index < links.length; index++) {
                    $(".ResulsTableCar tr:last").after("<tr><tr><td>" + links[index].driver_id + "</td> <td>" + data.drivers[index] +  "</td> <td>" +  links[index].created_at + "</td> </tr>");
                }
            }
            else 
            {
              $(".ResulsTableCar").html("No drivers connected to this car")
            }

          },
          error:   function(post){ console.log(this) }
        });
    }
}
function printTableCar()
{
        var optionValue =$(".cmbx_drivers").val();
         if (optionValue) {
      $.ajax({
          type:    "POST",
          url:     "/driversandcars/select_driver",
          data:    {optionValue: optionValue },
          success: function(data){
            var links=data.links 
            if(links.length!=0)
            {
                        $(".ResulsTableDriver").html("<tr><th>id</th><th>title</th><th>created_at</th></tr>")
                            for (index = 0; index < links.length; index++) {
        $(".ResulsTableDriver tr:last").after("<tr><td>" + links[index].car_id + "</td> <td>" + data.cars[index] +  "</td> <td>" +  links[index].created_at + "</td> </tr>");
    }
            }
            else{
              $(".ResulsTableDriver").html("No cars connected to this driver")

            }

          },
          error:   function(post){ console.log(this) }
        });
    }
}
    $("#submitBtn").click(function() {
 var car =$(".cmbx_cars").val();
  var driver =$(".cmbx_drivers").val();

         if (car&&driver) {
            $.ajax({
                type:    "POST",
                url:     "/driversandcars/submit",
                   data:    {car: car,driver:driver },
                success: function(data){ 

                   alert(data.text);   
                   printTableCar();  
                   printTbleDriver();             
                   },
                error:   function(post){ console.log(this) }
                });
         }
         else
         {
           alert("faild")
         }
    });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mycarsapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <%# <link href="cover.css" rel="stylesheet"> %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>

  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:30px;">
<a class="navbar-brand" href="/">
    <%=image_tag "home.png", style: 'height:auto;width:50px;'%> 
    MyCarsApp
  </a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/car/new">Add car</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/driver/new">Add driver</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/drivers">Drivers list</a>
      </li>
            <li class="nav-item">
        <a class="nav-link" href="/cars">Cars list</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="/driversandcars">Connect driver to car</a>
      </li>
    </ul>
  </div>
</nav>

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  
    <%= yield %>
    <footer class="mastfoot mt-auto">
        <div class="inner">
          
        </div>
      </footer>
</div>
  </body>
</html>

app/views/my_cars/myCars.html.erb
<h1>Home Page</h1>